import Foundation
import Testing
@testable import wisp

/// Byte-for-byte conformance with the zap.cooking frontend NIP-98 reference
/// (`src/lib/nip98.ts`). Golden values were generated by running that
/// module's exact logic (normalizeUrl / sha256Hex / authEvent encoding) in
/// Node — see ZAPCOOKING_ANDROID_BUILD.md §1. Ported verbatim from
/// Android `Nip98Test`.
struct Nip98Tests {

    @Test func normalizeUrl_dropsQueryAndFragment() {
        #expect(
            Nip98.normalizeUrl("https://zap.cooking/api/membership/check-status?pubkey=abc&x=1")
                == "https://zap.cooking/api/membership/check-status"
        )
    }

    @Test func normalizeUrl_stripsTrailingSlashOnNonRoot() {
        #expect(
            Nip98.normalizeUrl("https://zap.cooking/api/extract-recipe/")
                == "https://zap.cooking/api/extract-recipe"
        )
    }

    @Test func normalizeUrl_keepsRootSlash_evenWhenAbsent() {
        // JS `new URL('https://zap.cooking').pathname` === '/'.
        #expect(Nip98.normalizeUrl("https://zap.cooking") == "https://zap.cooking/")
        #expect(Nip98.normalizeUrl("https://zap.cooking/") == "https://zap.cooking/")
    }

    @Test func normalizeUrl_passesThroughCanonicalUrl() {
        #expect(
            Nip98.normalizeUrl("https://zap.cooking/api/membership/check-status")
                == "https://zap.cooking/api/membership/check-status"
        )
    }

    @Test func sha256Hex_matchesFrontendPayloadTag() {
        let body = "{\"pubkey\":\"79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798\"}"
        #expect(
            Nip98.sha256Hex(Data(body.utf8))
                == "5cce3a5f4dee312cc4272163bb61a5f35186a1b99f4d1c7d1bd88f5a80b48f69"
        )
    }

    @Test func buildTags_uppercasesMethodAndAddsPayload() {
        let tags = Nip98.buildTags(
            method: "post",
            url: "https://zap.cooking/api/membership/check-status?z=1",
            bodyString: "{\"pubkey\":\"79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798\"}"
        )
        #expect(tags == [
            ["u", "https://zap.cooking/api/membership/check-status"],
            ["method", "POST"],
            ["payload", "5cce3a5f4dee312cc4272163bb61a5f35186a1b99f4d1c7d1bd88f5a80b48f69"],
        ])
    }

    @Test func buildTags_omitsPayloadWhenNoBody() {
        let tags = Nip98.buildTags(
            method: "GET",
            url: "https://zap.cooking/api/membership/check-status",
            bodyString: nil
        )
        #expect(tags == [
            ["u", "https://zap.cooking/api/membership/check-status"],
            ["method", "GET"],
        ])
    }

    @Test func encodeAuthHeader_matchesFrontendByteForByte() {
        // Fixed, fully-specified signed event (sig is a stand-in — only the
        // serialization + base64 are under test here; signature validity is
        // verified by the live round-trip against check-status).
        let event = NostrEvent(
            id: "d1a2b3c4d5e6f70819a2b3c4d5e6f70819a2b3c4d5e6f70819a2b3c4d5e6f708",
            pubkey: "79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798",
            kind: Nip98.kind,
            createdAt: 1718600000,
            tags: [
                ["u", "https://zap.cooking/api/membership/check-status"],
                ["method", "POST"],
                ["payload", "5cce3a5f4dee312cc4272163bb61a5f35186a1b99f4d1c7d1bd88f5a80b48f69"],
            ],
            content: "",
            sig: String(repeating: "0123456789abcdef", count: 8)
        )
        let expected = "Nostr eyJpZCI6ImQxYTJiM2M0ZDVlNmY3MDgxOWEyYjNjNGQ1ZTZmNzA4MTlhMmIzYzRkNWU2"
            + "ZjcwODE5YTJiM2M0ZDVlNmY3MDgiLCJwdWJrZXkiOiI3OWJlNjY3ZWY5ZGNiYmFjNTVhMDYyOTVjZTg3MGIw"
            + "NzAyOWJmY2RiMmRjZTI4ZDk1OWYyODE1YjE2ZjgxNzk4IiwiY3JlYXRlZF9hdCI6MTcxODYwMDAwMCwia2lu"
            + "ZCI6MjcyMzUsInRhZ3MiOltbInUiLCJodHRwczovL3phcC5jb29raW5nL2FwaS9tZW1iZXJzaGlwL2NoZWNr"
            + "LXN0YXR1cyJdLFsibWV0aG9kIiwiUE9TVCJdLFsicGF5bG9hZCIsIjVjY2UzYTVmNGRlZTMxMmNjNDI3MjE2"
            + "M2JiNjFhNWYzNTE4NmExYjk5ZjRkMWM3ZDFiZDg4ZjVhODBiNDhmNjkiXV0sImNvbnRlbnQiOiIiLCJzaWci"
            + "OiIwMTIzNDU2Nzg5YWJjZGVmMDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWYwMTIzNDU2Nzg5YWJj"
            + "ZGVmMDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWYwMTIzNDU2Nzg5YWJjZGVmMDEyMzQ1Njc4OWFi"
            + "Y2RlZiJ9"
        #expect(Nip98.encodeAuthHeader(event) == expected)
    }
}
